# Generated by Django 3.0.4 on 2020-03-12 11:41

import core.image_paths
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('street', models.CharField(max_length=250)),
                ('building_number', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, choices=[('mt', 'Matruh'), ('al', 'Alexandria'), ('bh', 'Beheira'), ('ks', 'Kafr El Sheikh'), ('dk', 'Dakahlia'), ('da', 'Damietta'), ('ps', 'Port Said'), ('ns', 'North Sinai'), ('gr', 'Gharbia'), ('mo', 'Monufia'), ('qa', 'Qalyubia'), ('sh', 'Sharqia'), ('is', 'Ismailia'), ('gi', 'Giza'), ('fa', 'Faiyum'), ('ca', 'Cairo'), ('su', 'Suez'), ('ss', 'South Sinai'), ('bs', 'Beni Suef'), ('mi', 'Minya'), ('wa', 'El Wadi El Gedid'), ('as', 'Asyut'), ('rs', 'Red Sea'), ('so', 'Sohag'), ('qn', 'Qena'), ('lx', 'Luxor'), ('sw', 'Aswan')], max_length=3, null=True)),
                ('country', models.CharField(default='Egypt', max_length=250)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IDImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to=core.image_paths.id_image_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=core.image_paths.profile_image_path)),
                ('about', models.TextField(verbose_name='About you')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'unique': 'A phone number already exists.'}, max_length=128, null=True, region=None, unique=True)),
                ('transportation', models.CharField(blank=True, choices=[('b', 'Bicycle'), ('m', 'Motorcycle'), ('c', 'Car'), ('v', 'Van'), ('t', 'Truck')], max_length=1, null=True)),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other Gender')], max_length=1, null=True)),
                ('id_number', models.IntegerField(validators=[django.core.validators.MaxLengthValidator])),
                ('accept_terms', models.BooleanField(default=False)),
                ('is_tasker', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='users.Address')),
                ('id_images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_images', to='users.IDImages')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
