# Generated by Django 3.0.4 on 2020-03-12 15:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200312_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='About you'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_images', to='users.IDImages'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(14)]),
        ),
    ]
