# Generated by Django 3.0.4 on 2020-03-13 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_auto_20200312_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id_images',
        ),
        migrations.AddField(
            model_name='address',
            name='profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='idimages',
            name='id_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='id_images', to='users.Profile'),
            preserve_default=False,
        ),
    ]
