# Generated by Django 3.0.4 on 2020-03-13 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200313_1628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IDImages',
        ),
    ]
