# Generated by Django 3.0.4 on 2020-03-13 16:43

import core.image_paths
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_idimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to=core.image_paths.id_image_path)),
                ('id_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_images', to='users.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
