# Generated by Django 3.0.4 on 2020-03-13 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_idimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idimages',
            old_name='id_image',
            new_name='profile',
        ),
    ]
